const usStates = {
    1: {'abbr': 'AK', 'state': 'Alaska'},
    2: {'abbr': 'AL', 'state': 'Alabama'},
    3: {'abbr': 'AR', 'state': 'Arkansas'},
    4: {'abbr': 'AZ', 'state': 'Arizona'},
    5: {'abbr': 'CA', 'state': 'California'},
    6: {'abbr': 'CO', 'state': 'Colorado'},
    7: {'abbr': 'CT', 'state': 'Connecticut'},
    8: {'abbr': 'DC', 'state': 'District of Columbia'},
    9: {'abbr': 'DE', 'state': 'Delaware'},
    10: {'abbr': 'FL', 'state': 'Florida'},
    11: {'abbr': 'GA', 'state': 'Georgia'},
    12: {'abbr': 'HI', 'state': 'Hawaii'},
    13: {'abbr': 'IA', 'state': 'Iowa'},
    14: {'abbr': 'ID', 'state': 'Idaho'},
    15: {'abbr': 'IL', 'state': 'Illinois'},
    16: {'abbr': 'IN', 'state': 'Indiana'},
    17: {'abbr': 'KS', 'state': 'Kansas'},
    18: {'abbr': 'KY', 'state': 'Kentucky'},
    19: {'abbr': 'LA', 'state': 'Louisiana'},
    20: {'abbr': 'MA', 'state': 'Massachusetts'},
    21: {'abbr': 'MD', 'state': 'Maryland'},
    22: {'abbr': 'ME', 'state': 'Maine'},
    23: {'abbr': 'MI', 'state': 'Michigan'},
    24: {'abbr': 'MN', 'state': 'Minnesota'},
    25: {'abbr': 'MO', 'state': 'Missouri'},
    26: {'abbr': 'MS', 'state': 'Mississippi'},
    27: {'abbr': 'MT', 'state': 'Montana'},
    28: {'abbr': 'NC', 'state': 'North Carolina'},
    29: {'abbr': 'ND', 'state': 'North Dakota'},
    30: {'abbr': 'NE', 'state': 'Nebraska'},
    31: {'abbr': 'NH', 'state': 'New Hampshire'},
    32: {'abbr': 'NJ', 'state': 'New Jersey'},
    33: {'abbr': 'NM', 'state': 'New Mexico'},
    34: {'abbr': 'NV', 'state': 'Nevada'},
    35: {'abbr': 'NY', 'state': 'New York'},
    36: {'abbr': 'OH', 'state': 'Ohio'},
    37: {'abbr': 'OK', 'state': 'Oklahoma'},
    38: {'abbr': 'OR', 'state': 'Oregon'},
    39: {'abbr': 'PA', 'state': 'Pennsylvania'},
    40: {'abbr': 'PR', 'state': 'Puerto Rico'},
    41: {'abbr': 'RI', 'state': 'Rhode Island'},
    42: {'abbr': 'SC', 'state': 'South Carolina'},
    43: {'abbr': 'SD', 'state': 'South Dakota'},
    44: {'abbr': 'TN', 'state': 'Tennessee'},
    45: {'abbr': 'TX', 'state': 'Texas'},
    46: {'abbr': 'UT', 'state': 'Utah'},
    47: {'abbr': 'VA', 'state': 'Virginia'},
    48: {'abbr': 'VT', 'state': 'Vermont'},
    49: {'abbr': 'WA', 'state': 'Washington'},
    50: {'abbr': 'WI', 'state': 'Wisconsin'},
    51: {'abbr': 'WV', 'state': 'West Virginia'},
    52: {'abbr': 'WY', 'state': 'Wyoming'},
    53: {'abbr': 'Unknown', 'state': 'Unknown'},
}

export default usStates