const vehicleMakes = [
  'Acura',
  'Audi',
  'BMW',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Dodge',
  'FIAT',
  'Ford',
  'GMC',
  'Honda',
  'HUMMER',
  'Hyundai',
  'Infiniti',
  'Isuzu',
  'Jaguar',
  'Jeep',
  'Kia',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Mazda',
  'Mercedes-Benz',
  'Mercury',
  'MINI',
  'Mitsubishi',
  'Nissan',
  'Oldsmobile',
  'Plymouth',
  'Pontiac',
  'Porsche',
  'Ram',
  'Saab',
  'Saturn',
  'Scion',
  'Smart',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo'
]

const vehicleModels = {
  'Acura': [
    'CL',
    'Integra',
    'Legend',
    'MDX',
    'NSX',
    'RDX',
    'RL',
    'RSX',
    'SLX',
    'TL',
    'TSX',
    'Vigor',
    'ZDX',
  ],
  'Audi': [
    '80',
    '90',
    '100',
    '100',
    '200',
    '200',
    '4000',
    '4000CS Quattro',
    '4000s',
    '4000s Quattro',
    '5000CS',
    '5000CS Quattro',
    '5000S',
    '80/90',
    'A3',
    'A4',
    'A5',
    'A6',
    'A7',
    'A8',
    'Allroad',
    'Cabriolet',
    'Coupe GT',
    'Coupe Quattro',
    'Q5',
    'Q7',
    'Quattro',
    'R8',
    'riolet',
    'RS 4',
    'RS 6',
    'RS4',
    'RS6',
    'S4',
    'S5',
    'S6',
    'S8',
    'TT',
    'V8',
  ],
  'BMW': [
    '325',
    '330',
    '525',
    '530',
    '545',
    '550',
    '600',
    '645',
    '650',
    '745',
    '750',
    '760',
    '1 Series',
    '3 Series',
    '5 Series',
    '6 Series',
    '7 Series',
    '8 Series',
    'Alpina B7',
    'M',
    'M Roadster',
    'M3',
    'M5',
    'M6',
    'X3',
    'X5',
    'X5 M',
    'X6',
    'X6 M',
    'Z3',
    'Z4',
    'Z4 M',
    'Z4 M Roadster',
    'Z8',
  ],
  'Buick': [
    'Century',
    'Coachbuilder',
    'Electra',
    'Enclave',
    'Estate',
    'Hearse',
    'LaCrosse',
    'LeSabre',
    'Lucerne',
    'Park Avenue',
    'Rainier',
    'Reatta',
    'Regal',
    'Rendezvous',
    'Riviera',
    'Roadmaster',
    'Skyhawk',
    'Skylark',
    'Somerset',
    'Special',
    'Terraza',
    'Verano',
  ],
  'Cadillac': [
    'Century',
    'Coachbuilder',
    'Electra',
    'Enclave',
    'Estate',
    'Hearse',
    'LaCrosse',
    'LeSabre',
    'Lucerne',
    'Park Avenue',
    'Rainier',
    'Reatta',
    'Regal',
    'Rendezvous',
    'Riviera',
    'Roadmaster',
    'Skyhawk',
    'Skylark',
    'Somerset',
    'Special',
    'Terraza',
    'Verano',
  ],
  'Chevrolet': [
    '1500',
    '2500',
    '3500',
    'APV',
    'Astro',
    'Avalanche',
    'Avalanche 1500',
    'Avalanche 2500',
    'Aveo',
    'Bel Air',
    'Beretta',
    'Blazer',
    'Camaro',
    'Caprice',
    'Caprice Classic',
    'Cavalier',
    'Citation',
    'Classic',
    'Cobalt',
    'Cobalt SS',
    'Colorado',
    'Corsica',
    'Corvair',
    'Corvair 500',
    'Corvette',
    'Cruze',
    'Equinox',
    'Express',
    'Express 1500',
    'Express 2500',
    'Express 3500',
    'G-Series 1500',
    'G-Series 2500',
    'G-Series 3500',
    'G-Series G10',
    'G-Series G20',
    'G-Series G30',
    'HHR',
    'HHR Panel',
    'Impala',
    'Impala SS',
    'K5 Blazer',
    'Lumina',
    'Lumina APV',
    'LUV',
    'Malibu',
    'Malibu Maxx',
    'Metro',
    'Monte Carlo',
    'Monza',
    'Prizm',
    'S10',
    'S10 Blazer',
    'Silverado',
    'Silverado 1500',
    'Silverado 2500',
    'Silverado 3500',
    'Silverado 3500HD',
    'Silverado Hybrid',
    'Sonic',
    'Sportvan G10',
    'Sportvan G20',
    'Sportvan G30',
    'SSR',
    'Suburban',
    'Suburban 1500',
    'Suburban 2500',
    'Tahoe',
    'Tracker',
    'Trailblazer',
    'Traverse',
    'Uplander',
    'Vega',
    'Venture',
    'Volt',
  ],
  'Chrysler': [
    '200',
    '300',
    '300C',
    '300M',
    'Aspen',
    'Cirrus',
    'Concorde',
    'Crossfire',
    'Crossfire Roadster',
    'Fifth Ave',
    'Grand Voyager',
    'Imperial',
    'LeBaron',
    'LHS',
    'New Yorker',
    'Pacifica',
    'Prowler',
    'PT Cruiser',
    'Sebring',
    'Town & Country',
    'Voyager',
  ],
  'Dodge': [
    'Aries',
    'Aspen',
    'Avenger',
    'Caliber',
    'Caravan',
    'Challenger',
    'Charger',
    'Colt',
    'D150',
    'D150 Club',
    'D250',
    'D250 Club',
    'D350',
    'D350 Club',
    'Dakota',
    'Dakota Club',
    'Daytona',
    'Durango',
    'Dynasty',
    'Grand Caravan',
    'Intrepid',
    'Journey',
    'Magnum',
    'Monaco',
    'Neon',
    'Nitro',
    'Omni',
    'Ram',
    'Ram 1500',
    'Ram 1500 Club',
    'Ram 2500',
    'Ram 2500 Club',
    'Ram 3500',
    'Ram 3500 Club',
    'Ram 50',
    'Ram Van 1500',
    'Ram Van 2500',
    'Ram Van 3500',
    'Ram Van B150',
    'Ram Van B250',
    'Ram Van B350',
    'Ram Wagon B150',
    'Ram Wagon B250',
    'Ram Wagon B350',
    'Ramcharger',
    'Shadow',
    'Spirit',
    'Sprinter',
    'Stealth',
    'Stratus',
    'Viper',
    'Viper RT/10',
  ],
  'FIAT': [
    '500',
  ],
  'Ford': [
    'Aerostar',
    'Aspire',
    'Bronco',
    'Bronco II',
    'C-MAX Hybrid',
    'Club Wagon',
    'Contour',
    'Country',
    'Courier',
    'Crown Victoria',
    'E-350 Super Duty',
    'E-350 Super Duty Van',
    'E-Series',
    'E150',
    'E250',
    'E350',
    'Econoline E150',
    'Econoline E250',
    'Econoline E350',
    'Edge',
    'Escape',
    'Escort',
    'Escort ZX2',
    'Excursion',
    'EXP',
    'Expedition',
    'Expedition EL',
    'Explorer',
    'Explorer Sport',
    'Explorer Sport Trac',
    'F-250 Super Duty',
    'F-350 Super Duty',
    'F-Series',
    'F-Series Super Duty',
    'F150',
    'F250',
    'F350',
    'F450',
    'Fairlane',
    'Falcon',
    'Festiva',
    'Fiesta',
    'Five Hundred',
    'Flex',
    'Focus',
    'Focus ST',
    'Freestar',
    'Freestyle',
    'Fusion',
    'Galaxie',
    'GT',
    'GT500',
    'Laser',
    'Lightning',
    'LTD',
    'LTD Crown Victoria',
    'Model T',
    'Mustang',
    'Probe',
    'Ranger',
    'Taurus',
    'Taurus X',
    'Tempo',
    'Th!nk',
    'Thunderbird',
    'Torino',
    'Transit Connect',
    'Windstar',
    'ZX2',
  ],
  'GMC': [
    '1500',
    '2500',
    '3500',
    '1500 Club Coupe',
    '2500 Club Coupe',
    '3500 Club Coupe',
    'Acadia',
    'Canyon',
    'Envoy',
    'Envoy XL',
    'Envoy XUV',
    'EV1',
    'Jimmy',
    'Rally Wagon 1500',
    'Rally Wagon 2500',
    'Rally Wagon 3500',
    'Rally Wagon G2500',
    'Rally Wagon G3500',
    'Safari',
    'Savana',
    'Savana 1500',
    'Savana 2500',
    'Savana 3500',
    'Savana Cargo Van',
    'Sierra',
    'Sierra 1500',
    'Sierra 2500',
    'Sierra 2500HD',
    'Sierra 3500',
    'Sierra 3500HD',
    'Sierra Denali',
    'Sierra Hybrid',
    'Sonoma',
    'Sonoma Club',
    'Sonoma Club Coupe',
    'Suburban 1500',
    'Suburban 2500',
    'Terrain',
    'Vandura 1500',
    'Vandura 2500',
    'Vandura 3500',
    'Vandura G1500',
    'Vandura G2500',
    'Vandura G3500',
    'Yukon',
    'Yukon Denali',
    'Yukon XL',
    'Yukon XL 1500',
    'Yukon XL 2500',
  ],
  'Honda': [
    'Accord',
    'Accord Crosstour',
    'Civic',
    'Civic GX',
    'Civic Si',
    'CR-V',
    'CR-X',
    'CR-Z',
    'Crosstour',
    'del Sol',
    'Element',
    'FCX Clarity',
    'Fit',
    'Insight',
    'Odyssey',
    'Passport',
    'Pilot',
    'Prelude',
    'Ridgeline',
    'S2000',
  ],
  'HUMMER': [
    'H1',
    'H2',
    'H2 SUT',
    'H2 SUV',
    'H3',
    'H3T',
  ],
  'Hyundai': [
    'Accent',
    'Azera',
    'Elantra',
    'Entourage',
    'Equus',
    'Excel',
    'Genesis',
    'Genesis Coupe',
    'HED-5',
    'Santa Fe',
    'Scoupe',
    'Sonata',
    'Tiburon',
    'Tucson',
    'Veloster',
    'Veracruz',
    'XG300',
    'XG350',
  ],
  'Infiniti': [
    'Accent',
    'Azera',
    'Elantra',
    'Entourage',
    'Equus',
    'Excel',
    'Genesis',
    'Genesis Coupe',
    'HED-5',
    'Santa Fe',
    'Scoupe',
    'Sonata',
    'Tiburon',
    'Tucson',
    'Veloster',
    'Veracruz',
    'XG300',
    'XG350',
  ],
  'Isuzu': [
    'Amigo',
    'Ascender',
    'Axiom',
    'Hombre',
    'Hombre Space',
    'i-280',
    'i-290',
    'i-350',
    'i-370',
    'i-Series',
    'Impulse',
    'Oasis',
    'Rodeo',
    'Rodeo Sport',
    'Space',
    'Stylus',
    'Trooper',
    'VehiCROSS',
  ],
  'Jaguar': [
    'S-Type',
    'X-Type',
    'XF',
    'XJ',
    'XJ Series',
    'XK',
    'XK Series',
  ],
  'Jeep': [
    'Cherokee',
    'Comanche',
    'Commander',
    'Compass',
    'Grand Cherokee',
    'Liberty',
    'Patriot',
    'Wrangler',
  ],
  'Kia': [
    'Amanti',
    'Borrego',
    'Carens',
    'Forte',
    'Mentor',
    'Mohave/Borrego',
    'Optima',
    'Rio',
    'Rio5',
    'Rondo',
    'Sedona',
    'Sephia',
    'Sorento',
    'Soul',
    'Spectra',
    'Spectra5',
    'Sportage',
  ],
  'Land Rover': [
    'Amanti',
    'Borrego',
    'Carens',
    'Forte',
    'Mentor',
    'Mohave/Borrego',
    'Optima',
    'Rio',
    'Rio5',
    'Rondo',
    'Sedona',
    'Sephia',
    'Sorento',
    'Soul',
    'Spectra',
    'Spectra5',
    'Sportage',
  ],
  'Lexus': [
    'CT',
    'ES',
    'GS',
    'GX',
    'HS',
    'IS',
    'IS F',
    'IS-F',
    'LFA',
    'LS',
    'LS Hybrid',
    'LX',
    'RX',
    'RX Hybrid',
    'SC',
  ],
  'Lincoln': [
    'Aviator',
    'Blackwood',
    'Continental',
    'Continental Mark VII',
    'LS',
    'Mark LT',
    'Mark VII',
    'Mark VIII',
    'MKS',
    'MKT',
    'MKX',
    'MKZ',
    'Navigator',
    'Navigator L',
    'Town Car',
    'Zephyr',
  ],
  'Mazda': [
    '323',
    '626',
    '929',
    'B-Series',
    'B-Series Plus',
    'B2000',
    'B2500',
    'B2600',
    'CX-5',
    'CX-7',
    'CX-9',
    'Familia',
    'GLC',
    'Mazda2',
    'Mazda3',
    'Mazda5',
    'Mazda6',
    'Mazda6 5-Door',
    'Mazda6 Sport',
    'Mazdaspeed 3',
    'Mazdaspeed6',
    'Miata MX-5',
    'Millenia',
    'MPV',
    'MX-3',
    'MX-5',
    'MX-6',
    'Navajo',
    'Protege',
    'Protege5',
    'RX-7',
    'RX-8',
    'Tribute',
  ],
  'Mercedes-Benz': [
    '190E',
    '300CE',
    '300D',
    '300E',
    '300SD',
    '300SE',
    '300SL',
    '300TE',
    '400E',
    '400SE',
    '400SEL',
    '500E',
    '500SEC',
    '500SEL',
    '500SL',
    '600SEC',
    '600SEL',
    '600SL',
    'C-Class',
    'CL-Class',
    'CL65 AMG',
    'CLK-Class',
    'CLS-Class',
    'E-Class',
    'G-Class',
    'G55 AMG',
    'GL-Class',
    'GLK-Class',
    'M-Class',
    'R-Class',
    'S-Class',
    'SL-Class',
    'SL65 AMG',
    'SLK-Class',
    'SLK55 AMG',
    'SLR McLaren',
    'SLS AMG',
    'SLS-Class',
    'Sprinter',
    'Sprinter 2500',
    'Sprinter 3500',
    'W123',
    'W126',
    'W201',
  ],
  'Mercury': [
    'Capri',
    'Cougar',
    'Grand Marquis',
    'Lynx',
    'Marauder',
    'Mariner',
    'Marquis',
    'Milan',
    'Montego',
    'Monterey',
    'Mountaineer',
    'Mystique',
    'Sable',
    'Topaz',
    'Tracer',
    'Villager',
  ],
  'MINI': [
    'Clubman',
    'Cooper',
    'Cooper Clubman',
    'Cooper Countryman',
    'Countryman',
    'MINI',
  ],
  'Mitsubishi': [
    '3000GT',
    'Challenger',
    'Chariot',
    'Cordia',
    'Diamante',
    'Eclipse',
    'Endeavor',
    'Excel',
    'Expo',
    'Expo LRV',
    'Galant',
    'GTO',
    'i-MiEV',
    'L300',
    'Lancer',
    'Lancer Evolution',
    'Mighty Max',
    'Mighty Max Macro',
    'Mirage',
    'Montero',
    'Montero Sport',
    'Outlander',
    'Outlander Sport',
    'Pajero',
    'Precis',
    'Raider',
    'RVR',
    'Sigma',
    'Space',
    'Starion',
    'Tredia',
    'Truck',
    'Tundra',
  ],
  'Nissan': [
    '200SX',
    '240SX',
    '280ZX',
    '300ZX',
    '350Z',
    '350Z Roadster',
    '370Z',
    'Altima',
    'Armada',
    'Cube',
    'Datsun/Nissan Z-car',
    'Frontier',
    'GT-R',
    'JUKE',
    'Leaf',
    'Maxima',
    'Murano',
    'NV1500',
    'NV2500',
    'NV3500',
    'NX',
    'Pathfinder',
    'Pathfinder Armada',
    'Quest',
    'Rogue',
    'Sentra',
    'Stanza',
    'Titan',
    'Versa',
    'Xterra',
  ],
  'Oldsmobile': [
    '88',
    '98',
    'Achieva',
    'Alero',
    'Aurora',
    'Bravada',
    'Ciera',
    'Custom Cruiser',
    'Cutlass',
    'Cutlass Cruiser',
    'Cutlass Supreme',
    'Intrigue',
    'LSS',
    'Regency',
    'Silhouette',
    'Toronado',
  ],
  'Plymouth': [
    'Acclaim',
    'Breeze',
    'Colt',
    'Colt Vista',
    'Fury',
    'Grand Voyager',
    'Horizon',
    'Laser',
    'Neon',
    'Prowler',
    'Reliant',
    'Roadrunner',
    'Sundance',
    'Volare',
    'Voyager',
  ],
  'Pontiac': [
    '1000',
    '6000',
    'Aztek',
    'Bonneville',
    'Chevette',
    'Daewoo Kalos',
    'Fiero',
    'Firebird',
    'Firebird Formula',
    'Firebird Trans Am',
    'Firefly',
    'G3',
    'G5',
    'G6',
    'G8',
    'Gemini',
    'Grand Am',
    'Grand Prix',
    'Grand Prix Turbo',
    'GTO',
    'LeMans',
    'Montana',
    'Montana SV6',
    'Monterey',
    'Parisienne',
    'Safari',
    'Solstice',
    'Sunbird',
    'Sunfire',
    'Tempest',
    'Torrent',
    'Trans Sport',
    'Turbo Firefly',
    'Vibe',
  ],
  'Porsche': [
    '911',
    '914',
    '924',
    '928',
    '944',
    '968',
    '924 S',
    'Boxster',
    'Carrera GT',
    'Cayenne',
    'Cayman',
    'Panamera',
  ],
  'Ram': [
    '1500',
    '2500',
    '3500',
    'C/V',
    'Dakota',
  ],
  'Saab': [
    '900',
    '9000',
    '42981',
    '42981',
    '42983',
    '42983',
    '9-2X',
    '9-2X',
    '9-4X',
    '9-7X',
    '9-7X',
  ],
  'Saturn': [
    'Astra',
    'Aura',
    'Ion',
    'L-Series',
    'Outlook',
    'Relay',
    'S-Series',
    'Sky',
    'VUE',
  ],
  'Scion': [
    'FR-S',
    'iQ',
    'tC',
    'xA',
    'xB',
    'xD',
  ],
  'Smart': [
    'Fortwo',
  ],
  'Subaru': [
    'Alcyone SVX',
    'B9 Tribeca',
    'Baja',
    'Brat',
    'BRZ',
    'Forester',
    'Impreza',
    'Impreza WRX',
    'Justy',
    'Legacy',
    'Leone',
    'Loyale',
    'Outback',
    'Outback Sport',
    'SVX',
    'Tribeca',
    'XT',
      ],
      'Suzuki': [
    'Aerio',
    'Cultus',
    'Daewoo Lacetti',
    'Daewoo Magnus',
    'Equator',
    'Esteem',
    'Forenza',
    'Grand Vitara',
    'Kizashi',
    'Reno',
    'Samurai',
    'Sidekick',
    'SJ',
    'SJ 410',
    'Swift',
    'SX4',
    'Verona',
    'Vitara',
    'X-90',
    'XL-7',
    'XL7',
  ],
  'Tesla': [
    'Model S',
    'Roadster',
  ],
  'Toyota': [
    '4Runner',
    'Avalon',
    'Camry',
    'Camry Hybrid',
    'Camry Solara',
    'Celica',
    'Corolla',
    'Cressida',
    'Echo',
    'FJ Cruiser',
    'Highlander',
    'Highlander Hybrid',
    'Ipsum',
    'Land Cruiser',
    'Matrix',
    'MR2',
    'Paseo',
    'Previa',
    'Prius',
    'Prius c',
    'Prius Plug-in',
    'Prius Plug-in Hybrid',
    'Prius v',
    'RAV4',
    'Sequoia',
    'Sienna',
    'Solara',
    'Supra',
    'T100',
    'T100 Xtra',
    'Tacoma',
    'Tacoma Xtra',
    'Tercel',
    'Truck Xtracab SR5',
    'Tundra',
    'TundraMax',
    'Venza',
    'Xtra',
    'Yaris',
  ],
  'Volkswagen': [
    'Beetle',
    'Cabriolet',
    'CC',
    'Corrado',
    'Eos',
    'Eurovan',
    'Fox',
    'GLI',
    'Golf',
    'Golf III',
    'GTI',
    'Jetta',
    'Jetta III',
    'New Beetle',
    'Passat',
    'Phaeton',
    'Quantum',
    'R32',
    'Rabbit',
    'rio',
    'riolet',
    'Routan',
    'Scirocco',
    'Tiguan',
    'Touareg',
    'Touareg 2',
    'Type 2',
    'Vanagon',
  ],
  'Volvo': [
    '240',
    '740',
    '850',
    '940',
    '960',
    'C30',
    'C70',
    'S40',
    'S60',
    'S70',
    'S80',
    'S90',
    'V40',
    'V50',
    'V70',
    'V90',
    'XC60',
    'XC70',
    'XC90',
    'XC90',
  ],
}

export { vehicleMakes, vehicleModels }